modLoader="javafml"
loaderVersion="[46,47)"
license="AGPL-3.0"

[[mods]]
    modId="denseores"
    version="1.2.1"

    displayName="Dense Ores"
    authors="NewJumper"
    logoFile="banner.png"

    description='''Ores that drop more materials!'''

[[dependencies.denseores]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20, 1.21)"
    side="BOTH"

[[dependencies.denseores]]
    modId="forge"
    mandatory=true
    versionRange="[46,47)"
    side="BOTH"
