modLoader="javafml"
loaderVersion="[44,45)"
license="AGPL-3.0"

[[mods]]
    modId="denseores"
    version="1.2.1"

    displayName="Dense Ores"
    authors="NewJumper"
    logoFile="banner.png"

    description='''Ores that drop more materials!'''

[[dependencies.denseores]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3, 1.20)"
    side="BOTH"

[[dependencies.denseores]]
    modId="forge"
    mandatory=true
    versionRange="[44,45)"
    side="BOTH"
